Publish artifacts to GitHub releases (#51)
* Test github releases tag
* Input valid job name "github_releases"
* Update githubConnection name
* echo github_releases build variables
* Run github_releases job on conditions
  Add condition to github_releases job that it should run only win, linux & mac job succeeded
* Split github_releases to separate template
* Create list for dependsOn
  ERROR: Job github_releases depends on unknown job win linux mac .
* Echo build id
* Use buildId as tag name for draft release
* List items from ArtifactStagingDirectory dir
* Echo Build.ArtifactsDirectory
* Remove node v.8.12.x matrix
* Remove node v.8.12.x (win & linux)
* Change task "PublishPipelineArtifact@0"
  Publish artificats to pipeline, so that it can be used in later stages.
* Use variable $(tagName)
* Split into sub-scripts jobs
* Set tagSource to manual
* Echo few text messages
* Remove changelogs
* Add quote around variable
* Download pipeline artifacts (win, linux, mac)
* Split download pipeline artifact (win, linux, mac)
* Change githubrelease assets "System.ArtifactsDirectory"
* List item from System.ArtifactsDirectory
* Change directory to $(System.ArtifactsDirectory)/dist
* Create & copy selective files to deploy directory
* Remove test script commands
* Add os name to download pipeline artifacts task
* Get all files and exclude few of them
* Specify the files to gh releases
* Remove "-" from items
* List files from dist
* matches zero or more characters within a file or directory name
* Ignore file type .blockmap
* Remove extra comments
* Run github_releases job on master branch only